model:
  name: gcn
  kwargs:
    num_conv_layers: 2
    num_lin_layers: 1
    hid_features: [16, 16]

sampler:
  name: DataLoader

wrapper:
  name: Graph
  kwargs:
    learning_rate: 0.002

trainer:
  dir: ../logs
  accelerator: cpu
  devices: 1
  max_epochs: 100
