model:
  name: jsgc 
  kwargs:
    jump_degree: 7

sampler:
  name: SGC
  degree: 6
  jump: true
  train:
      num_parts: 1
  test:
      num_parts: 1

wrapper:
  name: GraphLinear
  kwargs:
    learning_rate: 0.001
    weight_decay: 0.01

trainer:
  dir: ../logs
  accelerator: cpu
  devices: 1
  max_epochs: 1400 
