model:
  name: sgc 
  kwargs: {}

sampler:
  name: SGC
  degree: 6
  train:
      num_parts: 1
  val:
      num_parts: 1
  test:
      num_parts: 1

wrapper:
  name: GraphLinear
  kwargs:
    learning_rate: 0.003
    weight_decay: 0.26

trainer:
  dir: ../logs
  accelerator: cpu
  devices: 1
  max_epochs: 6000 
