model:
  name: sgc
  kwargs: {}

sampler:
  name: SGC
  degree: 7
  train:
    num_parts: 1
  val:
    num_parts: 1
  test:
    num_parts: 1

wrapper:
  name: GraphLinear
  kwargs:
    learning_rate: 0.1
    weight_decay: 0.015

trainer:
  dir: ../logs
  accelerator: cpu
  devices: 1
  max_epochs: 10000 
