model:
  name: sgc 
  kwargs: {}

sampler:
  name: SGC
  degree: 2
  train:
    num_parts: 16 
  val:
    num_parts: 4 

wrapper:
  name: Linear 
  kwargs:
    learning_rate: 0.002
    weight_decay: 0.04

trainer:
  dir: ../logs
  accelerator: cpu
  devices: 1
  max_epochs: 100
