model:
  name: psgc 
  kwargs: {}

sampler:
  name: GraphSGC
  degree: 4
  train:
    batch_size: 20
  test:
    batch_size: 20

wrapper:
  name: PoolLinear
  kwargs:
    learning_rate: 0.01
    weight_decay: 0.01

trainer:
  dir: ../logs
  accelerator: cpu
  devices: 1
  max_epochs: 200
