model:
  name: gcn
  kwargs:
    num_conv_layers: 2
    num_lin_layers: 1
    hid_features: [20, 20]

sampler:
  name: SGC
  degree: 1
  train:
    num_parts: 1
  test:
    num_parts: 1

wrapper:
  name: Graph 
  kwargs:
    learning_rate: 0.001

trainer:
  dir: ../logs
  accelerator: cpu
  devices: 1
  max_epochs: 3000
